services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=eventos_db'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=eventos_user'
    ports:
      - '8371:5432'
    volumes:
      - postgres_data:/var/lib/postgresql

volumes:
  postgres_data:
